### ISSUE TITLE
Deis Workflow deis-builder component fails to start

### ISSUE THREAD

**Issue by kloudtaxi** [TheNewNormal/kube-solo-osx#110]
deis-builder fails to spin up in v0.8.3 with the following message. 

2016-07-13T02:32:39.709661147Z 2016/07/13 02:32:39 Error getting storage parameters (read /var/run/secrets/deis/objectstore/creds/..7987_12_07_19_53_36.730762557: is a directory)

desi-builder version info.
quay.io/deis/builder:v2.1.0

**Comment by rimusz** [comment]
known issue it should be fix in the new Deis Workflow v2.2 release https://github.com/deis/builder/pull/382

**Comment by kloudtaxi** [comment]
thanks for the info. will keep an eye out for it.

**Comment by rimusz** [comment]
let's keep it open, so other users can notice the issue

**Comment by rimusz** [comment]
the new Deis Workflow v2.2.0 works fine now, so closing the issue
