### ISSUE TITLE
Allow using CLI version of corectl

### ISSUE THREAD

**Issue by RaeesBhatti** [TheNewNormal/kube-solo-osx#116]
Kube-Solo-OSX requires you to install the `.app` version of `corectl` which is [not really necessary](https://github.com/TheNewNormal/corectl/blob/10bc03f862e37237d27c5510ee277ad04215c5d7/README.md#via-homebrews). And the `brew install corectl` version does not work as a result.
We can do `which corectl` and `which corectld` and use those path to start daemon and execute commands.

**Comment by RaeesBhatti** [comment]
It will actually be easier to upgrade too, one could do a `brew upgrade corectl` rather than visiting the releases page and downloading and installing manually.

**Comment by RaeesBhatti** [comment]
Ref: #117

**Comment by rimusz** [comment]
The `corectl.app` was made intentionally to avoid `brew install corectl` stuff. As there are three Apps depending on `corectld` having a dedicated `corectl.app` makes more sense.
Plus we do not want people to force and install `brew` as not everybody is using it.
Also `corectl.app` has the option via menu `Check for corectld updates` which downloads the latest version of `corectl` tools so you do not have visit releases page and downloading and installing manually. 

The `visit releases page and downloading and installing` only applies for `corectl.app` itself.
