### ISSUE TITLE
NoSuchFileException: /var/run/secrets/kubernetes.io/serviceaccount/token

### ISSUE THREAD

**Issue by rroopreddy** [TheNewNormal/kube-solo-osx#12]
Thank you, kube-solo-osx that is light on resources and is a nice way to experiment with kubernetes on mac. 

Running some examples emit the following error

WARN  17:41:57 Request to kubernetes apiserver failed
java.nio.file.NoSuchFileException: /var/run/secrets/kubernetes.io/serviceaccount/token

It seems like other containers are now relying on  /var/run/secrets/kubernetes.io/serviceaccount/token, which is initialized by default with "kube-up.sh". Is it possible to do the same with "kube-solo-osx" initialization

**Comment by rimusz** [comment]
sure, I will take a look, it should be possible to implement

**Comment by rimusz** [comment]
@rroopreddy does not look that `kube-up.sh' creates any service account, it depends on the examples
you are trying to run needs. You need to create some service account e.g.:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  name: somename
```

**Comment by rroopreddy** [comment]
@rimusz This is getting created somewhere part of kube_up.sh invocation. , I see the following on on AWS Kubernetes cluster I started with "kube_up.sh"

$:~/cluster-deployment/kubernetes$ ./cluster/kubectl.sh get secrets
NAME                  TYPE                                  DATA      AGE
default-token-kcb4i   kubernetes.io/service-account-token   2         7d

$:~/cluster-deployment/kubernetes$ ./cluster/kubectl.sh get serviceaccount
NAME      SECRETS   AGE
default   1         7d

**Comment by rimusz** [comment]
Can you please provide an example you are trying to run?

**Comment by rroopreddy** [comment]
examples/cassandra from the kubernetes examples folder

On Tue, Dec 1, 2015 at 8:48 AM, Rimas Mocevicius notifications@github.com
wrote:

> Can you please provide an example you are trying to run?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/TheNewNormal/kube-solo-osx/issues/12#issuecomment-161027957
> .

## 

Regards,
☼ Ravi
