### ISSUE TITLE
[question] Mounting local directories to VM

### ISSUE THREAD

**Issue by whitlockjc** [TheNewNormal/kube-solo-osx#123]
While working on enabling authn, I want to run [dex](https://github.com/coreos/dex) within the VM.  To allow me to work on a dev build, I wanted to mount some host directory within the VM so I could run dex via a Service Unit by altering `~/kube-solo/cloud-init/user-data`.  Can you tell me how to do this?

I'm currently looking at the sources so I might end up figuring it out myself.  I've tried a few things already and spent enough time on it to see if I could get help.

**Comment by rimusz** [comment]
just use `nfs` volume `/Users/my_user:/Users/my_user`

**Comment by whitlockjc** [comment]
That will work just fine, I forgot you were mounting this.  Thanks a lot.

**Comment by whitlockjc** [comment]
I'm not sure this is working and it could be my own issue.  Whenever my service tries to start, I get this: `/Users/notyou/workspaces/go/src/github.com/coreos/dex/bin/dex-worker: No such file or directory`  I'm not saying there is a kube-solo issue but I'm not having luck.  Here is my modification to `~/kube-solo/cloud-init/user-data`:

```
    - name: dex.service
      command: start
      content: |
        [Unit]
        Description=Dex
        Documentation=https://github.com/coreos/dex
        Requires=etcd2.service docker.service flanneld.service persistent-data-checks.service
        After=etcd2.service docker.service flanneld.service persistent-data-checks.service
        [Service]
        ExecStart=/Users/notyou/workspaces/go/src/github.com/coreos/dex/bin/dex-worker \
          --tls-cert-file=/Users/notyou/kube-solo/certs/dex.pem \
          --tls-key-file=/Users/notyou/kube-solo/certs/dex-key.pem \
          --listen="https://0.0.0.0:5556" \
          --issuer="https://127.0.0.1:5556" \
          --clients=/Users/notyou/workspaces/go/src/github.com/coreos/dex/static/fixtures/clients.json.sample \
          --connectors=/Users/notyou/workspaces/go/src/github.com/coreos/dex/static/fixtures/connectors.json.sample \
          --email-cfg=/Users/notyou/workspaces/go/src/github.com/coreos/dex/static/fixtures/emailer.json \
          --users=/Users/notyou/workspaces/go/src/github.com/coreos/dex/static/fixtures/users.json.sample \
          --html-assets=/Users/notyou/workspaces/go/src/github.com/coreos/dex/static/html \
          --no-db
        Restart=always
        RestartSec=10
```

Of course, I also updated `apiserver.service` to depend on `dex.service`.

**Comment by whitlockjc** [comment]
I think I ran into some environmental issue that caused `corectl.app` to bust and `kube-solo.app` to bust as well.  Blowing them both away, reinstalling the latest versions and now `/Users/notyou` is mounted as expected.  No idea what Gremlins were in my machine but it _appears_ to be fixed.

**Comment by rimusz** [comment]
those f..k Gremlins are always the problem :)
