### ISSUE TITLE
Latest release cannot start VM

### ISSUE THREAD

**Issue by whitlockjc** [TheNewNormal/kube-solo-osx#124]
I just updated to the latest kube-solo and when attempting to bring up the VM, I get this:

```
reating 20GB sparse disk (QCow2)...
/Applications/Kube-Solo.app/Contents/Resources/functions.sh: line 152: /Users/notyou/bin/qcow-tool: No such file or directory
-
Created  Data disk


Starting VM ...

/Applications/Kube-Solo.app/Contents/Resources/functions.sh: line 195: /Users/notyou/bin/corectl: No such file or directory

VM has not booted, please check '~/kube-solo/logs/vm_up.log' and report the problem !!!
```

I've updated to the latest corectl as well but nothing works.

**Comment by rimusz** [comment]
hmm, this is something todo with `corectl.app`, as it copies it's files to `~/bin` folder.
kube-solo app does not have those files by itself anymore

**Comment by whitlockjc** [comment]
I think my corectl.app was borked.  I updated it too and when it started, it never prompted me for my password so I assume it just wasn't running.

**Comment by rimusz** [comment]
phew

**Comment by whitlockjc** [comment]
It was weird because starting the newly updated `corectl.app` didn't prompt an error but once I saw that its status wasn't `Server is running`, I got the idea that maybe it was borked.  Force quit and restart seems to have fixed it.

**Comment by harobed** [comment]
Same error here, I've reinstalled corectl.app but `~/bin/` is always empty.
