### ISSUE TITLE
external-ip stuck in pending state

### ISSUE THREAD

**Issue by rrva** [TheNewNormal/kube-solo-osx#128]
More of a general kubernetes question, is something additional needed for the wordpress service in this tutorial: https://github.com/kubernetes/kubernetes/tree/master/examples/mysql-wordpress-pd/ to automatically have an external ip assigned? external-ip stays forever in `<pending>` status. According to the tutorial it should get an external ip assigned.

I can however access the service through 192.168.64.14:31437 (`<node ip>:<node port>`)

This is how the service looks like after being deployed according to the tutorial:

```
 kubectl get service wordpress
NAME        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
wordpress   10.100.20.207   <pending>     80/TCP    17h

$ kubectl describe service wordpress
Name:                   wordpress
Namespace:              default
Labels:                 app=wordpress
Selector:               app=wordpress,tier=frontend
Type:                   LoadBalancer
IP:                     10.100.20.207
Port:                   <unset> 80/TCP
NodePort:               <unset> 31437/TCP
Endpoints:              10.244.87.6:80
Session Affinity:       None
No events.
```

**Comment by rimusz** [comment]
loadbalancer/external IP is cloud provider feature, it will only work with GCP, AWS and Azure.

**Comment by rrva** [comment]
Ok, I guess closing this one. It's unfortunate that some things are not available in the same way locally.

**Comment by rimusz** [comment]
it is nothing to do with the Kubernetes or this VM :)
