### ISSUE TITLE
Possible to run k8s on the command line instead of using the app?

### ISSUE THREAD

**Issue by quinncomendant** [TheNewNormal/kube-solo-osx#133]
Is it possible to run Kubernetes on `corectl` via kube-solo entirely via the command line, instead of using the app? I have been using `corectl` directly instead of using the coreos-osx app. I prefer the transparency of knowing what's going on, to learn the sysadmin aspect that will translate to managing Kubernetes on real servers. Is kube-solo-osx good for learning the commands for running Kubernetes directly?

PS: Any other channel for having these kind of discussions - are you guys on Slack/IRC?

**Comment by rimusz** [comment]
yes, after app install you can use cli to control VM, as per readme:
After successful install you can control kube-solo VM via ksolo cli as well. Cli resides in ~/kube-solo/bin and ~/bin foldersand has simple commands: ksolo start|stop|status|ip|ssh, just add ~/bin to your pre-set path.

**Comment by rimusz** [comment]
we usually hang out at kubernetes slack

**Comment by rimusz** [comment]
we can close this one, as it answered your question :)
