### ISSUE TITLE
Update homebrew formula

### ISSUE THREAD

**Issue by quinncomendant** [TheNewNormal/kube-solo-osx#134]
Current homebrew formula installs 0.9.1. Is updating this recipe to use the new version the responsibility of someone on your team? 

Also, I wonder why it doesn't auto-include new releases despite using an appcast feed (`appcast 'https://github.com/TheNewNormal/kube-solo-osx/releases.atom'`). Probably I don't know how appcast works.

**Comment by rimusz** [comment]
sorry it is not me who does homebrew formula or nether anybody from our team. must be some other person does it time by time. so i'm closing this one
