### ISSUE TITLE
iTerm requirement

### ISSUE THREAD

**Issue by intellix** [TheNewNormal/kube-solo-osx#135]
Noticed that Kube up opened up iTerm. Installed Kube and then removed iTerm, hoping my next stuff would just use the native OSX Terminal. Opening shell etc stopped working, so I tried to restart and then ended up having to delete ~/kube-solo. This was when I noticed that iTerm is being installed by Kube Solo.

Is there any reason why Kube Solo depends on iTerm and installs it? There's no mention in the docs at all that it's required and I can't see what it does extra that can't be accomplished by the native Terminal itself.

**Comment by rimusz** [comment]
I used to have the iTerm as a requirement, but guys always forgot to install it and always there an issue opened that app does not work, so I included it with the app, so no needs to install by yourself. Most of user and myself found iTerm more user friendly comparing to Terminal.
Sure I will update docs that iTerm is needed, if not found it will be installed for you.
PR is welcome to support both :)

**Comment by rimusz** [comment]
readme updated
