### ISSUE TITLE
Install fails with missing file k8solo-01.toml

### ISSUE THREAD

**Issue by mkarliner** [TheNewNormal/kube-solo-osx#142]
Attempting to UP the VM for the first time I get.

/Applications/Kube-Solo.app/Contents/Resources/up.command; exit;
cat: /Users/mike/kube-solo/settings/k8solo-01.toml: No such file or directory
/Applications/Kube-Solo.app/Contents/Resources/functions.sh: line 18: /Users/mike/kube-solo/settings/k8solo-01.toml: No such file or directory

Starting k8solo-01 VM ...

Data disk does not exist, it will be created now ...

Please type Data disk size in GBs followed by [ENTER]:
[default is 30]:
## Creating 30GB sparse disk (QCow2)...

Created 30GB Data disk

Starting VM ...

[WARN] unable to run "defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist" Shared_Net_Address ...
[WARN] ... assuming macOS default value (192.168.64.1)
[WARN] unable to run "defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist" Shared_Net_Mask ...
[WARN] ... assuming macOS default value (255.255.255.0)
[ERROR] open settings/k8solo-01.toml: no such file or directory

VM has not booted, please check '~/kube-solo/logs/vm_up.log' and report the problem !!!

Press [Enter] key to continue...

The logs tell the same story...

**Comment by rimusz** [comment]
interesting issue, why the `k8solo-01.toml` is not there, need to add a check for that file, if not found, copy it from app's bundle.

Can you try to delete `/Users/mike/kube-solo` folder and try again, please. thanks

**Comment by mkarliner** [comment]
I did delete and try again, the log was from the second attempt. I should also mention that the settings sub-directory is not being created either.

**Comment by rimusz** [comment]
interesting, as there is a shell [command](https://github.com/TheNewNormal/kube-solo-osx/blob/master/src/kube-solo-install.command#L12) to create that folder.
are you using bash, zsh, or other shell?

**Comment by mkarliner** [comment]
I'm using bash.
I should also mention I'm using docker for Mac beta.

After creating settings and copying k8solo over, my next attempt gave

Starting VM ...

[WARN] unable to run "defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist" Shared_Net_Address ...
[WARN] ... assuming macOS default value (192.168.64.1)
[WARN] unable to run "defaults read /Library/Preferences/SystemConfiguration/com.apple.vmnet.plist" Shared_Net_Mask ...
[WARN] ... assuming macOS default value (255.255.255.0)

> booting k8solo-01 (1/1)
> [ERROR] stat /Users/mike/kube-solo/cloud-init/user-data: no such file or directory

VM has not booted, please check '~/kube-solo/logs/vm_up.log' and report the problem !!!

Press [Enter] key to continue...

**Comment by rimusz** [comment]
docker for Mac does not make any difference for kube-solo app,
as [corectl](https://github.com/TheNewNormal/corectl]) tool is based on Docker HypertKit too.
Booth are using the same native macOS Hypervisor.

It looks like something really weird is going on on your mac.

Usually I try the reboot and see what happens

**Comment by mkarliner** [comment]
Rebooted, re-initialised. This time it hangs on 'waiting for Kubernetes cluster to be ready' This can take a bit.

After an hour I gave up.

**Comment by rimusz** [comment]
still strange that happens for you only, will try to recheck the k8s initial install part, which was solid for months

**Comment by mkarliner** [comment]
I've now done an upgrade to 10.11.6 and I can start k8solo. 
It's worth mentioning that corectl still doesn't start correctly on boot,
it asks for a password and then cannot start the server. If I try to start 
again, it then works.

**Comment by rimusz** [comment]
phew, cool. yes I see that for `corectl` too, @AntonioMeireles is aware of it (he is `corectl` maintainer)

**Comment by rimusz** [comment]
@mkarliner the kube-solo should not hang on `waiting for Kubernetes cluster to be ready` , fixed it in #146

**Comment by rimusz** [comment]
also looking to `that corectl still doesn't start correctly on boot` https://github.com/TheNewNormal/corectl.app/issues/39
