### ISSUE TITLE
“up.command” can’t be opened because it is from an unidentified developer.

### ISSUE THREAD

**Issue by ishantanu** [TheNewNormal/kube-solo-osx#151]
I am unable to start the VM after the latest update of k8solo v0.9.9.
This was working till v0.9.8.

**Comment by rimusz** [comment]
hmm, strange one, will make a new app dmg soon

**Comment by rimusz** [comment]
@iamShantanu101 can you please download k8solo v0.9.9 again, I uploaded rebuilt version, thanks

**Comment by ishantanu** [comment]
@rimusz Still same error.

**Comment by rimusz** [comment]
can you provide some more detailed setup on your side

**Comment by ishantanu** [comment]
@rimusz This was fixed when the I restarted the system. But the reason behind this is still unknown.

**Comment by rimusz** [comment]
maybe so macos glitch
