### ISSUE TITLE
type: "LoadBalancer" isn't working. 

### ISSUE THREAD

**Issue by ishantanu** [TheNewNormal/kube-solo-osx#152]
When I tried to assign an external IP using type: "LoadBalancer" to a service, it doesn't work.
The External IP never gets assigned to it. 
Instead it keeps on displaying <pending> state.
I waited for a couple of hours but it still kept on showing the same state.

**Comment by rimusz** [comment]
Loadbalancer is cloud provider feature, e.g.GCP, AWS, it will not work on any kube app or any vagrant based setup

**Comment by ishantanu** [comment]
What about Nodeport?

**Comment by rimusz** [comment]
yup
