### ISSUE TITLE
Restart brakes k8s dashboard and pod to api authentication?

### ISSUE THREAD

**Issue by sputnick** [TheNewNormal/kube-solo-osx#154]
In v0.9.9 I'm having a strange issue. After first boot of kube-solo the k8s dashboard comes up fine. Then after a Halt and Up restart it no longer works (no endpoints "code": 503).

k8s dashboard pod logs say:

> Starting HTTP server on port 9090
> Creating API server client for https://10.100.0.1:443
> Error while initializing connection to Kubernetes apiserver. This most likely means that the cluster is misconfigured (e.g., it has invalid apiserver certificates or service accounts configuration) or the --apiserver-host param points to a server that does not exist. Reason: the server has asked for the client to provide credentials
> 

I'm testing Helm in a Pod so I remove the Tiller service and Tiller-Deploy after a fresh restart and start an RC with helm that will install Tiller again that matches its version. The very first time this works as planned e.g. by using kubectl exec myhelmpod helm init

If I restart kube-solo not only will the dashboard now be broken but I also get helm errors about the api server needed authentication...

**Comment by sputnick** [comment]
This is easily reproducible. I deleted kube-solo folder and started over and created a new "cluster" and waited until the dashboard was up. Then Halted and Up and now the dashboard doesn't work. I didn't install anything in between.

**Comment by rimusz** [comment]
thanks for reporting, yes I get the same problem with the Dashboard after VMs reboot.
Hmm nothing works in `kube-system` namespace.
Need to investigate it why.

**Comment by sputnick** [comment]
Ok "good" that it also breaks for you. And just FYI if this info matters from kubectl version:

> Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:38:40Z", GoVersion:"go1.7.1", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"v1.4.5", GitCommit:"5a0a696437ad35c133c0c8493f7e9d22b0f9b81b", GitTreeState:"clean", BuildDate:"2016-10-29T01:32:42Z", GoVersion:"go1.6.3", Compiler:"gc", Platform:"linux/amd64"}

**Comment by ktamiola** [comment]
The same here. Could the issue be related to _etcd_ ?

**Comment by rimusz** [comment]
fixed in v1.0.0
