### ISSUE TITLE
Notification Style

### ISSUE THREAD

**Issue by franz-josef-kaiser** [TheNewNormal/kube-solo-osx#155]
Currently the Notifications used to indicate the _off_ state, say:

> VM is OFF !!!

I do not really understand why _Kube Solo_ is in panic mode when I turn off the VM. Can we have this without three exclamation marks? 

> Multiple exclamation marks,' he went on, shaking his head, 'are a sure sign of a diseased mind.'

_– Terry Prachett_

**Comment by rimusz** [comment]
it is not in panic mode, it is just encoded text :)

**Comment by franz-josef-kaiser** [comment]
@rimusz Let's just [change this](https://github.com/TheNewNormal/kube-solo-osx/blob/78d930a3989aa156995065d1765a603f11fc345d/src/Kube-Solo/en.lproj/Localizable.strings) to a more relaxed voice. Does this sound like a plan? :)

**Comment by franz-josef-kaiser** [comment]
See #157 for a matching PR.
