### ISSUE TITLE
Helm install stable/jenkins fails because of SecurityContext

### ISSUE THREAD

**Issue by sputnick** [TheNewNormal/kube-solo-osx#160]
If you try to install Jenkins from stable/jenkins with Helm on Kube-Solo it fails to create its Pod with the error:
```Error creating: pods "" is forbidden: pod.Spec.SecurityContext.RunAsUser is forbidden```

It seems that support for SecurityContext is turned off? Saw this line kube-apiserver.service on the coreos vm. 
```admission_control=NamespaceLifecycle,NamespaceAutoProvision,LimitRanger,SecurityContextDeny,ServiceAccount,ResourceQuota```

Since stable charts are what most everyone will try with Kube-Solo shouldn't this be enabled?

**Comment by rimusz** [comment]
could you try to delete `SecurityContextDeny`  https://github.com/TheNewNormal/kube-solo-osx/blob/master/src/cloud-init/user-data#L168 in `~/kube-solo/cloud-init/user-data` and check if that fixes for you. if it does I will cut a new app version.
thanks

**Comment by sputnick** [comment]
Hey @rimusz I deleted SecurityContextDeny and restarted the cluster and now it works to install Jenkins :). Well as long as you disable persistent storage but that's another story...

Would be great to get this built into a new release.

cheers
Eiki

**Comment by rimusz** [comment]
i'm off this week, will do it when i'm  back

**Comment by rimusz** [comment]
fixed in https://github.com/TheNewNormal/kube-solo-osx/releases/tag/v1.0.1
