### ISSUE TITLE
[docs] explain difference with Minikube

### ISSUE THREAD

**Issue by vincent-dm** [TheNewNormal/kube-solo-osx#161]
Hi,

I'm just getting started with K8s and want to share my perspective: I've stumbled upon this project but also found the Minikube project, which seems more popular.

Reading your homepage doesn't explain to me at all why I should use Kube-Solo instead of (the officially supported) Minikube. (I'm using OSX)

Adding one or two sentences about the pros (and cons?) would greatly aid newcomers to decide which tool to use.

I know I could find out myself by spending time with both tools, but as I'm getting started with containerization, there are a million choices to be made. A short rationale could greatly help steer people to adopt your tool.

**Comment by rimusz** [comment]
hey there, there are many different local k8s solutions. it is not up to me to tell users to use kube-solo app instead of minikube.

**Comment by mikelnrd** [comment]
Hi I'm similar to the OP, looking to run k8s on my mac for local development and have found minikube and kube-solo/kube-cluster. I would have also liked something to explain how they compare to the officially supported minikube. Please (re)-consider adding this.

**Comment by mikelnrd** [comment]
(PS... I assume I can install both, but perhaps a note to say this or to warn people against it if they can't both exist side-by-side)

**Comment by vincent-dm** [comment]
@rimusz I understand that you don't want to do marketing to try to convince people to use kube-solo (I applaud that attitude). Nevertheless, I believe that a short, objective list of what differentiates kube-solo from minikube, and the pros/cons of using it would be useful.

**Comment by rimusz** [comment]
added a short text about kube-solo and minikube difference

**Comment by spundun** [comment]
From minikube's docs https://kubernetes.io/docs/getting-started-guides/minikube/ here are some listed features. It'd be useful to assert whether all these are supported by kube solo or not and if there are any features on top of this that kube solo supports.

Minikube Features
Minikube supports Kubernetes features such as:
DNS
NodePorts
ConfigMaps and Secrets
Dashboards
Container Runtime: Docker, and rkt
Enabling CNI (Container Network Interface)
Ingress
