### ISSUE TITLE
Not able to upgrade kubernetes to 1.7

### ISSUE THREAD

**Issue by b-rajesh** [TheNewNormal/kube-solo-osx#178]
Hi, 

I tried to upgrade my kubernetes using kube solo to 1.7 and my solo stopped working and keep giving this message in loop

The connection to the server 192.168.64.2:8080 was refused - did you specify the right host or port

Any help ?

**Comment by rimusz** [comment]
`kube-solo` only supports etcd v2 for now (needs work on it), kubernetes v 1.6 and v1.7 only work with etcd v3

**Comment by b-rajesh** [comment]
thank you
