### ISSUE TITLE
Hangs at "waiting for VM to be ready"

### ISSUE THREAD

**Issue by olalonde** [TheNewNormal/kube-solo-osx#20]
I clicked the "up" menu option for the first time and it's hangs at "Waiting for VM to be ready..." for >5 mins. Any idea of what might be wrong?

```
Starting VM ...

> booting k8solo-01
[corectl] alpha/928.0.0 already available on your system
Error: unable to validate /etc/exports ('[]')

Usage:
  corectl load path/to/yourProfile [flags]

Examples:
  corectl load profiles/demo.toml

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Error: 'k8solo-01' not found, or dead

Usage:
  corectl query [VMids] [flags]

Aliases:
  query, q

Flags:
  -a, --all    display extended information about a running CoreOS instance
  -i, --ip     displays given instance IP address
  -j, --json   outputs in JSON for easy 3rd party integration

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"

Error: 'k8solo-01' not found, or dead

Usage:
  corectl query [VMids] [flags]

Aliases:
  query, q

Flags:
  -a, --all    display extended information about a running CoreOS instance
  -i, --ip     displays given instance IP address
  -j, --json   outputs in JSON for easy 3rd party integration

Global Flags:
      --debug   adds extra verbosity, and options, for debugging purposes and/or power users

All flags can also be configured via upper-case environment variables prefixed with "COREOS_"
For example, "--debug" => "COREOS_DEBUG"


Waiting for VM to be ready...
```

**Comment by AntonioMeireles** [comment]
@olalonde hi, thanks for reporting! 

what did you had/have in /etc/exports before ? could you paste it here please ?. (also, you're running latest version of kube-solo-osx, right ?)

**Comment by rimusz** [comment]
@olalonde which OS X 10.10 or 10.11 you have ?

**Comment by olalonde** [comment]
Thanks for the reply. 

I'm on OS X 10.11 and using the latest version of `kube-solo-osx`. VirtualBox 5.0.0r101573

@AntonioMeireles there was indeed something in my `/etc/exports` which I was using for my docker-machine setup (https://gist.github.com/olalonde/74de9d053448b977f77e).

This is the current content of my `/etc/exports`:

```
~$ cat /etc/exports
/Users -mapall=olalonde:staff 192.168.0.104

/Users -network 192.168.64.0 -mask 255.255.255.0 -alldirs -mapall=501:20
```

**Comment by AntonioMeireles** [comment]
@olalonde i guess that if you comment the 1st line things would work. Can you confirm please ?(the issue here is that parent dir is already exported when we're trying to export _just_ your `$homedir`). will try to figure a way to handle this smoothly.

**Comment by olalonde** [comment]
Thanks that worked! 

By the way, is this project related to https://github.com/rimusz/coreos-osx-kubernetes-cluster? They both seem similar though it's hard to tell which one inspired the other.

**Comment by rimusz** [comment]
yes, both projects are mine. the kube-solo is based on `corect/xhyve` so this why it got moved to the new thenewnormal github org, which is for `corectl`tool and Apps based on it. I'm porting `coreos-osx-kubernetes-cluster` to `corect/xhyve` as well, so that project in future will removed to thenewnormal github org

**Comment by olalonde** [comment]
Thanks
