### ISSUE TITLE
Feature request: tmux integration

### ISSUE THREAD

**Issue by olalonde** [TheNewNormal/kube-solo-osx#22]
My iTerm2 profile is configured with **Send text at start:** `tmux attach -t base || tmux new -s base`, which automatically attaches to or launches a tmux session. Which means that when kube-solo-osx tries to launch commands in my terminal, it doesn't work (it just opens a new tab in iTerm2 which attaches to my tmux session and nothing else happens). Would it be possible to configure the app to open a new tmux window instead of trying to launch iTerm2?

**Comment by rimusz** [comment]
I need to think how to use tmux, as I do not want to break App's work for everybody else who do not use tmux

**Comment by olalonde** [comment]
Understood. Maybe if you could point me to the bash script I would need to edit to make this work, I could try to figure something out. If I need to touch Obj-C code though, I'm useless

**Comment by rimusz** [comment]
this one https://github.com/TheNewNormal/kube-solo-osx/blob/master/src/up.command gets called the you do `Up`
