### ISSUE TITLE
Quitting the app doesn't kill xhyve processes

### ISSUE THREAD

**Issue by slack** [TheNewNormal/kube-solo-osx#3]
I quit the kube-solo app and it left xhyve running in the background. Subsequent launches of the app confused matters worse.

**Comment by rimusz** [comment]
what exactly happened there?

**Comment by slack** [comment]
Clicked App Dropdown -> Quit

Then from a process listing, I still saw a bunch of xhyve instances running.

**Comment by rimusz** [comment]
fixed in v0.1.4
