### ISSUE TITLE
Not able to start VM because of /etc/exports

### ISSUE THREAD

**Issue by westende** [TheNewNormal/kube-solo-osx#30]
First of all thank you for your efforts trying to make development on Kubernetes this easy on OSX.

I am now still doing a lot of development using Vagrant & Virtualbox. Therefor there are some Vagrant generated entries in my /etc/exports. With these entries the VM does not boot up. When I remove these, the VM does boot up.

I have not yet looked at the code, so I'm not sure if this is a problem within this project or maybe in a dependency.

```
Starting VM ...
> booting k8solo-01
[corectl] alpha/942.0.0 already available on your system
Error: unable to validate /etc/exports ('[]'
```

**Comment by AntonioMeireles** [comment]
@piepkrak 

Hi! could you please paste here your existing `/etc/exports` ?. For some reason it isn't passing our smoke tests... And many _thanks_!

**Comment by westende** [comment]
Hi! Hereby my /etc/exports file. I changed the names of projects for privacy reasons

```
# VAGRANT-END: 1296 c54aa86a-465e-4f78-9aad-48a29863e115
# VAGRANT-BEGIN: 1296 15ac914e-c8b3-46ed-8941-0350ba2bd05e
"/Users/user/projects/vagrant/name/www" 192.168.33.10 -alldirs -mapall=1296:20
# VAGRANT-END: 1296 15ac914e-c8b3-46ed-8941-0350ba2bd05e
# VAGRANT-BEGIN: 1296 a52297b2-6b9c-469f-9c0b-188a0dae00a5
"/Users/user/projects/vagrant/name/www" 192.168.33.10 -alldirs -mapall=1296:20
# VAGRANT-END: 1296 a52297b2-6b9c-469f-9c0b-188a0dae00a5
# VAGRANT-BEGIN: 1296 c54aa86a-465e-4f78-9aad-48a29863e115
"/Users/user/projects/vagrant/name-name-name/www" 192.168.33.30 -alldirs -mapall=1296:20
# VAGRANT-END: 1296 c54aa86a-465e-4f78-9aad-48a29863e115
# VAGRANT-BEGIN: 1296 7682421c-c919-42b5-9610-820797c79b01
"/Users/user/projects/vagrant/name/www" 192.168.33.10 -alldirs -mapall=1296:20
# VAGRANT-END: 1296 7682421c-c919-42b5-9610-820797c79b01
# VAGRANT-BEGIN: 1296 4ae87ab9-16c5-424f-94a4-20ebce7e2c4b
"/Users/user/projects/vagrant/name/application" 192.168.33.20 -alldirs -mapall=1296:20
# VAGRANT-END: 1296 4ae87ab9-16c5-424f-94a4-20ebce7e2c4b
# VAGRANT-BEGIN: 1296 f22e491f-73b1-47bc-8668-a25cc0f7ed69
"/Users/user/projects/vagrant/name/simplesamlphp" 192.168.33.10 -alldirs -mapall=1296:20
"/Users/user/projects/vagrant/name/www" 192.168.33.10 -alldirs -mapall=1296:20
# VAGRANT-END: 1296 f22e491f-73b1-47bc-8668-a25cc0f7ed69
```

**Comment by wstrange** [comment]
FWIW, I also had an issue with kube-solo and my /etc/exports. The install would bomb out.

In my case I just discarded the entry that Vagrant put in - so I don't have it anymore. I suspect there is an issue parsing the format.

**Comment by wstrange** [comment]
A lateral thought...

Is sudo needed just for /etc/exports?

It might be better to not save the sudo password.  The user presumably would need to provide it once to fix up exports - but after that it should not be needed. Might be safer.

**Comment by rimusz** [comment]
@wstrange sudo password is needed for corectl/xhyve to boot VMs

**Comment by AntonioMeireles** [comment]
@piepkrak 

the issue here is that `corectl` expects to be able to export via NFS `${HOME}` and that fails because a subdir (actually in your case, quite a few ones) of it is already set as exported (via Vagrant). Unless there is a way,in OS X, that i'm unware of, of exporting at same time both a dir  and a subdir of it, i think that the best i can do here is just print a more meaningfull failure message telling that we're unable to export `${HOME}` because some dir inside it is already exported.

**Comment by rimusz** [comment]
@AntonioMeireles such message would be really nice to have and then the VM's boot should continue

**Comment by AntonioMeireles** [comment]
@rimusz, 
long(er) story short - having a warning/check is a good thing to have, OTOH allowing VMs to boot without `${HOME}` being properly exported on host tricky as a lot of functionality ends depending on just that ... Will need a carefull deep look.

**Comment by westende** [comment]
@AntonioMeireles Thank you for the explanation. I've never encountered this before. Will just swap the /etc/exports files for now.

**Comment by davidmankin** [comment]
Thanks.  This bit me too because I use Vagrant.  Would be nice to be able to make a special dir not under my homedir and export that to avoid conflicts.

**Comment by rimusz** [comment]
@AntonioMeireles is working on some solution :)

**Comment by elementalvoid** [comment]
In my case the conflict is with https://github.com/nlf/dlite.

```
# BEGIN: dlite
/Users -network 192.168.64.0 -mask 255.255.255.0 -alldirs -maproot=root:wheel                                                                                   
# END: dlite
```

**Comment by cmoad** [comment]
I'm also experiencing a conflict with dlite as mentioned by @elementalvoid.

**Comment by rimusz** [comment]
@piepkrak NFS is disabled, so should not be the issue anymore
