### ISSUE TITLE
Private Docker registry

### ISSUE THREAD

**Issue by whitlockjc** [TheNewNormal/kube-solo-osx#34]
Thanks a lot for your work.  I was wondering if you've had any thoughts about running a local Docker registry that Kubernetes is configured to use.  This would simplify development/testing quite a bit because you could build an image on the host system, push to the Docker registry and create a new pod/service deployment for Kubernetes without having to do all of the SSH dancing mentioned in TheNewNormal/kube-cluster-osx/issues/9.

**Comment by whitlockjc** [comment]
I think I just found out you already do this: _"Kube-Solo App can be used together with CoreOS VM App which allows to build Docker containers and has a private local Docker registry v2 which is accessible from Kube-Solo App."_  Feel free to close this once you confirm.

**Comment by whitlockjc** [comment]
I'm an idiot.  I see that this VM along with the _CoreOS VM App_ gives me what I need.  Sorry about the noise.

**Comment by whitlockjc** [comment]
I'm going to reopen this because things still aren't working and I'd like to see if we can get this figured out.  When I run the _CoreOS VM App_, I do indeed have a Docker Registry.  But when I try to `docker push`, I get the following:

```
The push refers to a repository [192.168.64.1:5000/testing] (len: 1)
unable to ping registry endpoint https://192.168.64.1:5000/v0/
v2 ping attempt failed with error: Get https://192.168.64.1:5000/v2/: tls: oversized record received with length 20527
 v1 ping attempt failed with error: Get https://192.168.64.1:5000/v1/_ping: tls: oversized record received with length 20527
```

If I use `http` to access the Docker Registry API, it works fine.  _(This test was performed via the browser.)_

Also, the more I think about this the more I realize that the initial request is still somewhat valid.  It would be slick of kube-solo-osx had a private Docker Registry running in it and the Kubernetes configured to use it.

**Comment by rimusz** [comment]
@whitlockjc docker registry in CoreOS OSX App is configured to work without `https`, do not see any point of it for the private local registry.

I do not include private registry in kube-solo as there is kube-cluster app too, which needs to access to docker registry.

coreos app is used to build docker containers and has the private registry docker images to be pushed to, then images can be reused by kube apps.

If there is a demand to have a separate docker registry App, I can make it up, but for now nobody else have asked for it.

**Comment by rimusz** [comment]
I was thinking how to make better use of private docker registry. One more small I think will be too much to have.
What I'm going to do is separate the `coreos VM` boot and docker registry start.
I will add an extra menu options to `coreos VM` App to start/stop docker registry,
that will allow build docker images and push to registry, then stop `coreos VM` and
still able to reuse docker registry from `kube Apps`

**Comment by whitlockjc** [comment]
I get you.  There's no need to bulk up the kube-solo but I'm still wondering why my attempt to `docker push` results in errors and it _appears_ to be because the Docker Registry isn't running via https.  I say _"appears"_ because of the error and because I have no expertise in the area to confirm one way or another.

I'm all for keeping two VMs for the reasons you stated but I do think we'll need to sort out the reason that `docker push` does not work with the Docker Registry running on the CoreOS VM.  Thoughts?

**Comment by rimusz** [comment]
docker registry works on CoreOS VM just fine, but just does not use the `https`, so use `http` and you will be fine.
As mentioned before I do not see any point use `https` for the local docker registry setup, no needs to complicate things

**Comment by whitlockjc** [comment]
So what do I need to do for things to work?  I just run `docker push` right now and `docker` is the one forcing, or assuming, https.  I'll keep googling.  Thanks again.

**Comment by rimusz** [comment]
I use registry on `CoreOS VM` e.g. like this:

```
$ docker pull alpine
Using default tag: latest
latest: Pulling from library/alpine

2314ad3eeb90: Pull complete
Digest: sha256:d7201bdfa765bebed9a79c385db4378f55593e50dc8d002b9713810320ad93b9
Status: Downloaded newer image for alpine:latest

$ docker tag alpine 192.168.64.1:5000/alpine

$ docker push 192.168.64.1:5000/alpine
The push refers to a repository [192.168.64.1:5000/alpine] (len: 1)
2314ad3eeb90: Image successfully pushed
latest: digest: sha256:dded5fb5deaf6f7b186a84841e76d2340391a202618dd9697688ef4d9a1b2f21 size: 1369
```

As you see it works just fine

**Comment by whitlockjc** [comment]
Cool.  Maybe since I never used `docker pull`, something wasn't setup properly.  I just built an image locally and then tried to push it.  I'll try your approach and if you don't hear from me, things are working fine.

**Comment by whitlockjc** [comment]
The fix was to unset `DOCKER_TLS_VERIFY` and `DOCKER_CERT_PATH`.  This could use some documentation and I'd be happy to add it if you want.  Here is a working example: `DOCKER_HOST=tcp://192.168.64.3:2375 DOCKER_TLS_VERIFY= DOCKER_CERT_PATH= ~/coreos-osx/bin/docker ps`  Of course, if I just run `DOCKER_HOST=tcp://192.168.64.3:2375 ~/coreos-osx/bin/docker ps`, that's when I get the error related to `oversized record received with length 20527`.  Every person on my team ran into this so I'm sure it's somewhat common, especially if you already run `docker-machine` as it's the tool that is setting these `DOCKER_*` environment variables.

**Comment by rimusz** [comment]
ah, `docker-machine` again, this is why I do not use it as I like my default shell to be clean.
I will release a new version next week with `DOCKER_TLS_VERIFY= DOCKER_CERT_PATH=` in preset shell.

**Comment by whitlockjc** [comment]
I think that would help, or even documenting something to the effect of _"Coexisting with docker-machine"_ or _"Migrating from docker-machine"_.  Regardless, thanks for all of your help and I'm glad I was able to figure it out.

**Comment by rimusz** [comment]
@whitlockjc https://github.com/TheNewNormal/coreos-osx/releases/tag/v1.2.2 automatically presets: 

```
DOCKER_TLS_VERIFY= 
DOCKER_CERT_PATH=
```

Please check it out and let me know if any issues you have encountered
