### ISSUE TITLE
kubectl bin script overrides context

### ISSUE THREAD

**Issue by jchauncey** [TheNewNormal/kube-solo-osx#36]
So just ran into an issue where I wanted to override the envvar KUBECONFIG and pass in my own file. However, kubectl in `~/kube-solo/bin/kubectl` overrides that with a command line flag. Much confusion was had.

**Comment by rimusz** [comment]
yup, it does do that to ignore your ~/.kube/config and then kubectl can connect to kube-solo master correctly

**Comment by whitlockjc** [comment]
Is this still up for debate?  I just ran into this situation as well when attempting to update `~/.kube/config` to connect to another k8s environment.  I updated the file as expected, tried to `kubectl config use-context my-new-context` only to have it fail.  I remembered setting my environment to use the `kubectl` from kube-solo and when I looked into it, it's a shell script that sets `--kubeconfig` to always use `$HOME/kube-solo/kube/kubeconfig`.  I'd really love to avoid having one k8s configuration file for kube-solo and another for the rest of my k8s environments but I defer to your judgement.

**Comment by rimusz** [comment]
@whitlockjc as I have mentioned above kube-solo does not touch your `/.kube/config`, when you open `Preset OS Shell` via App then `$HOME/kube-solo/kube/kubeconfig` is used. If you open another shell window not via App then your kubectl will look to `/.kube/config`. As in that way you can work with two k8s clusters at once.

**Comment by jchauncey** [comment]
Just don't symlink the kubesolo kubectl to your path and your fine.
