### ISSUE TITLE
Multiple Nodes

### ISSUE THREAD

**Issue by stevesloka** [TheNewNormal/kube-solo-osx#4]
I understand the project is "solo", but how hard do you think it would be to allow for multiple nodes? =)

When demoing (without wifi say at a conference), I typically want to have everything local. I've had varied success with the current offerings via Vagrant (works great, then need internet to eventually reboot everything).

I'm happy to help contribute the work, just thought I'd ask to see your thoughts on multiple nodes. (2-3 max).

~ Steve

**Comment by rimusz** [comment]
@stevesloka yes vagrant sucks without network, this is why I made xhyve based one Apps.
I'm thinking to convert my https://github.com/rimusz/coreos-osx-gui-kubernetes-cluster one to xhyve too, but xhyve is not so easy dealing with getting IPs. Will start working on it at some time as next week I'm going to San Francisco DevOps days and KubeCon, the Barcelona DockerCon and Distributed Matters. Need to find time for it :)

**Comment by stevesloka** [comment]
Awesome awesome good to hear. I'm completely new to xhyve so I will look to dig in and see what I can come up with. If there's ever something that I can help out with would love to. Thanks again for the really cool app!

**Comment by rimusz** [comment]
@stevesloka also take a look to https://github.com/rimusz/coreos-osx-gui which is great to build docker/rkt images and has built in docker registry, so you can use docker images for this App k8s cluster

**Comment by stevesloka** [comment]
Ohh very cool. I built a separate VM to do just that. I think I need to just figure out a way to deploy k8s on local CoreOS vms and I'll be happier, that way my restarts / shutdowns should be better. I'll check this out as well.
