### ISSUE TITLE
Can't get the dashboard working

### ISSUE THREAD

**Issue by ianwalter** [TheNewNormal/kube-solo-osx#45]
I get the following response:

``` json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "endpoints \"kubernetes-dashboard\" not found",
  "reason": "NotFound",
  "details": {
    "name": "kubernetes-dashboard",
    "kind": "endpoints"
  },
  "code": 404
}
```

**Comment by rimusz** [comment]
might be still in downloading of containers process
check with `kubectl --namespace=kube-system get po` for pod `kubernetes-dashboard-v1.0.0`

**Comment by ianwalter** [comment]
I think my laptop was on a shaky connection. I tried on my desktop and was able to get everything set up successfully.
