### ISSUE TITLE
deis launched applications unreachable from host

### ISSUE THREAD

**Issue by markTward** [TheNewNormal/kube-solo-osx#46]
I discover kube-solo-osx today from a deis blog post.  The ultimate intent in experimenting with kube-solo was to have a fast path for working with deis.  Toward that, I've received a mostly successful result, but am having an issuing reaching my launched services.

I've followed through the kube-solo and install_deis process successfully.  I then was able to create and deploy using 'deis create' and 'git push deis master' from one of the example apps.  

However, I'm unable to reach the running service from the host machine using the service clusterIP.  After sshing into the guest vm, I am able to reach the running service.

Am I supposed to be able reach my services running from kube-solo vm kubernetes cluster from the host?  Are there are recommendations for how to diagnose and fix this issue.  Please let me know what collection of diagnostics that might help.

Thanks for creating a straight forward process and tools for launching a cluster and deis!

**Comment by rimusz** [comment]
@markTward Deis Apps usually are accessed in the case of Kube-Solo via router IP, as there is no LoadBalancer.
e.g. app_name.kube-solo_ip.xip.io
