### ISSUE TITLE
kube-solo wants to write my laptop's password to filesystem

### ISSUE THREAD

**Issue by brendandburns** [TheNewNormal/kube-solo-osx#5]
I really can't let it do this, I'd much rather be prompted for the password when required.

**Comment by rimusz** [comment]
@brendandburns it gets annoying to type the password twice:
1) to get mac address via uuid
2) to start VM with xhyve
as both need sudo

I'm looking for other solutions to get rid of asking/saving user's password to be used for sudo

**Comment by brendandburns** [comment]
understood, but the security policy for my laptop forbids things like this, so I need some sort of solution no matter how annoying...

Maybe you can use the OS X keychain somehow?

**Comment by rimusz** [comment]
@brendandburns maybe for the start I can ask at the install part to save or not to save the password and work from there with two different options

**Comment by brendandburns** [comment]
sgtm.  thanks

**Comment by rimusz** [comment]
@brendandburns cool, I got keychain working fine, but a bit stuck on replacing python web server to go based
go based web server works fine for my other App, so the strange problem with this App :)

**Comment by rimusz** [comment]
@brendandburns fixed with v0.1.8
