### ISSUE TITLE
Docker local repository unreachable 

### ISSUE THREAD

**Issue by kvacquier** [TheNewNormal/kube-solo-osx#69]
I've tried to push a docker container built on the k8solo machine (via the sh) and now i would like to push it to use it in my replication controller (it's a custom one). 
Built with : docker build -t localhost:5000/my_container:0.1 -f Dockerfile  .
When i try to push it (i believe to local host) i only have Put http://localhost:5000/v1/repositories/my_container/: dial tcp 127.0.0.1:5000: getsockopt: connection refused (i've tried with mutilples ports)

Any Idea ??

**Comment by rimusz** [comment]
@kvacquier do you have local docker registry running?

**Comment by kvacquier** [comment]
Isn't it automaticaly launched ?

**Comment by rimusz** [comment]
nope, kube-solo does not have it. but you can use my other app CoreOS VM, with it you can build docker images and it has the local docker registry which is accessible for the kube-solo

**Comment by rimusz** [comment]
this not the issue, so I'm closing it
