### ISSUE TITLE
kube-solo halts unexpectedly

### ISSUE THREAD

**Issue by mboersma** [TheNewNormal/kube-solo-osx#73]
While using kube-solo v0.6.4 (and earlier versions), I often see the k8s api become unresponsive. All I can tell is that the VM has halted. If I click the "Up" menu item, kube-solo starts up as if nothing were wrong.

This happens often and easily--my test case is running the workflow-v2.0.0-e2e chart on top of Deis workflow-v2.0.0. Let me know if there are any logs I can provide. I have also tried configuring with 4GB of RAM allocated to kube-solo instead of the default 2GB, but same results.

**Comment by rimusz** [comment]
@mboersma can you provide the exact steps, so I can try to reproduce it. thanks

**Comment by mboersma** [comment]
@rimusz here's what I do:
1. Install latest kube-solo
2. Delete /etc/exports
3. Go through kube-solo initial setup (allocate 4GB RAM, 30GB disk)
4. Install the workflow-v2.0.0 chart with `helmc`
5. Install the workflow-v2.0.0-e2e chart and let the tests run

Reliably, somewhere in the middle of the test run there will be an unexpected error, or the suite will just stall. Looking at kube-solo shows that the k8s API no longer answers because the VM is halted.

This is also reproducible through normal Deis Workflow usage for me, without running tests. I'm not able to keep the instance running for more than 20-30 minutes max without this occurring. Usually starting up the VM again makes everything available, but the problem will recur.

Any specific logs or other info I can add?

**Comment by rimusz** [comment]
@AntonioMeireles ping, any ideas why the `corectl` could crash after running for 30 min, I'm not able to reproduce it yet.

**Comment by AntonioMeireles** [comment]
humm. this doesn't seem a deterministic issue here too. 

@mboersma - for context and to try to scope this issue - OS X version/RAM & hw version ?(not an hackintosh, right ?) . do you get anything in the system logs (command-space > console > search for corectl)  ? thanks!

**Comment by mboersma** [comment]
I'll try again with [v0.6.6](https://github.com/TheNewNormal/kube-solo-osx/releases/tag/v0.6.6) and add more detail here if I can reproduce the issue.

**Comment by mboersma** [comment]
It did happen to me again with v0.6.6 of kube-solo, following the steps I described above. This time I used the workflow-dev and workflow-dev-e2e charts. At the start of the workflow-e2e tests, the VM apparently halted. The console app had this:

``` console
6/15/16 9:07:31.956 AM sudo[1782]:     matt : TTY=ttys001 ; PWD=/Users/matt/kube-solo ; USER=root ; COMMAND=/Applications/Kube-Solo.app/Contents/Resources/bin/corectl load settings/k8solo-01.toml
6/15/16 9:07:33.216 AM InternetSharing[1787]: corectl: com.apple.NetworkSharing.broadcast-0 has been started
6/15/16 9:07:33.217 AM InternetSharing[1787]: corectl: com.apple.NetworkSharing.broadcast-0 (idle) has been stopped
6/15/16 9:07:33.752 AM InternetSharing[1787]: corectl: com.apple.NetworkSharing.broadcast-1 has been started
6/15/16 9:08:30.000 AM kernel[0]: process corectl[1794] caught causing excessive wakeups. Observed wakeups rate (per sec): 785; Maximum permitted wakeups rate (per sec): 150; Observation period: 300 seconds; Task lifetime number of wakeups: 45012
6/15/16 9:08:34.477 AM spindump[774]: Saved wakeups_resource.diag report for corectl version ??? (???) to /Library/Logs/DiagnosticReports/corectl_2016-06-15-090834_gradishar.wakeups_resource.diag
6/15/16 9:25:58.122 AM InternetSharing[1787]: corectl: com.apple.NetworkSharing.broadcast-1 (idle) has been stopped
6/15/16 9:26:14.024 AM sudo[3917]:     matt : TTY=ttys003 ; PWD=/Users/matt/kube-solo ; USER=root ; COMMAND=/Applications/Kube-Solo.app/Contents/Resources/bin/corectl load settings/k8solo-01.toml
6/15/16 9:26:14.130 AM InternetSharing[1787]: corectl: com.apple.NetworkSharing.broadcast-2 has been started
6/15/16 9:26:14.130 AM InternetSharing[1787]: corectl: com.apple.NetworkSharing.broadcast-2 (idle) has been stopped
6/15/16 9:26:14.480 AM InternetSharing[1787]: corectl: com.apple.NetworkSharing.broadcast-3 has been started
```

The 9:25 `has been stopped` message seems to correspond with the VM halting, after which I chose the "Up" menu item in kube-solo to bring it up again.

Macintosh is MacBook Pro retina 13", late 2013, 2.8 GhZ Core i7, 16GB RAM, OS X El Capitan 10.11.5. Kube-solo got 4GB RAM, 30GB disk.

**Comment by rimusz** [comment]
@mboersma please try the latest v0.8.0 it is based on the latest corectl v0.7.x with a separate server daemon and client.

**Comment by mboersma** [comment]
I haven't seen this happen with the new separate corectl. I'll keep an eye out. Thanks @rimusz!

**Comment by rimusz** [comment]
awesome
