### ISSUE TITLE
/etc/exports blocks install

### ISSUE THREAD

**Issue by huggsboson** [TheNewNormal/kube-solo-osx#81]
I used docker-machine-nfs which left the following entries in my /etc/exports:
$ cat /etc/exports

/Users 192.168.99.100 -alldirs -mapall=563785388:1221986466
/Users 192.168.99.106 -alldirs -mapall=563785388:1221986466
/Users 192.168.99.101 -alldirs -mapall=563785388:1221986466

Note the blank line.  I was consistently getting an error from corectl about not being able to parse /etc/exports ([]).  Might be worth fixing.

**Comment by huggsboson** [comment]
Note: I worked around by removing all lines from /etc/exports

**Comment by rimusz** [comment]
@huggsboson we are going to make NFS as an optional very soon, that should make easier to use `corectl` based apps then
https://github.com/TheNewNormal/coreos-osx/issues/76

**Comment by rimusz** [comment]
dupe of #30
