### ISSUE TITLE
Nice. Roadmap ?

### ISSUE THREAD

**Issue by ghost** [TheNewNormal/kube-solo-osx#9]
This is great. 

Will this allow easy deployment to providers. I need to push out to cge using gcloid and kubectl.

**Comment by ghost** [comment]
I mean gcloud. Oops

**Comment by rimusz** [comment]
@gedw99 this is purely done for local kubernetes manifests as rc, services and etc testing.
You can point your kubectl to GCE cluster when you have tested locally and create kubernetes services in the cloud then.

**Comment by ghost** [comment]
OK thanks. I will try it out
