### ISSUE TITLE
v0.8.0 kube-ui not started

### ISSUE THREAD

**Issue by cobrowserAlex** [TheNewNormal/kube-solo-osx#99]
I did a fresh install of 0.8.0 and found that kube-ui is not started:

```
bash-3.2$ kubectl --namespace=kube-system get po
NAME                                READY     STATUS    RESTARTS   AGE
kube-dns-v11-75rxn                  4/4       Running   1          52m
kubedash-2697969532-htxgl           2/2       Running   0          52m
kubernetes-dashboard-v1.1.0-hjrut   1/1       Running   0          52m
```

**Comment by rimusz** [comment]
@cobrowserAlex kube-ui was replaced by kubernetes-dashboard a while ago already

**Comment by cobrowserAlex** [comment]
Sorry, I meant kube-dashboard. So I guess it's loaded, just shows an error after a fresh install.
![kubernetes dashboard](https://cloud.githubusercontent.com/assets/10495775/16732623/663eeab8-477e-11e6-885d-e7e915a67f1b.png)
